services:
  - type: web
    name: vitaltrack-frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    envVars:
      - key: REACT_APP_SPRING_IP
        value: https://vitaltrack-backend.onrender.com/

  - type: web
    name: vitaltrack-backend
    env: docker
    plan: free
    dockerfilePath: back_end/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
