services:
  - type: web
    name: vitaltrack-frontend
    env: docker
    plan: free
    dockerfilePath: Dockerfile.frontend
    envVars:
      - key: REACT_APP_SPRING_IP
        value: https://vitaltrack-backend.onrender.com/

  - type: web
    name: vitaltrack-backend
    env: docker
    plan: free
    dockerfilePath: back_end/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: dAOzXnOxzHtTZDEzbVIITmoxXArYyVRL
