services:
  - type: web
    name: vitaltrack-frontend
    env: docker
    plan: free
    dockerfilePath: front_end/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: nginx -g 'daemon off;'
    envVars:
      - key: REACT_APP_SPRING_IP
        value: https://vitaltrack-backend.onrender.com/

  - type: web
    name: vitaltrack-backend
    env: docker
    plan: free
    dockerfilePath: back_end/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-mysql-host:3306/vitaltrack
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: abcd1234
