server:
  port: 4000
  tomcat:
    additional-tld-skip-patterns: '*.jar'
spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  servlet:
    multipart:
      max-file-size: "10MB"
      enabled: true
firebase:
  api-key: ${FIREBASE_API_KEY}
  auth-domain: ${FIREBASE_AUTH_DOMAIN}
  database-url: ${FIREBASE_DATABASE_URL}
  project-id: ${FIREBASE_PROJECT_ID}
  storage-bucket: ${FIREBASE_STORAGE_BUCKET}
  messaging-sender-id: ${FIREBASE_MESSAGING_SENDER_ID}
  app-id: ${FIREBASE_APP_ID}
