server:
  port: 8000
  tomcat:
    additional-tld-skip-patterns: '*.jar'
logging:
  pattern:
    console:  "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework: INFO
    root: INFO
spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  servlet:
    multipart:
      max-file-size: "10MB"
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/vitaltrack
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
  mybatis:
    mapper-locations: classpath:mappers/*.xml
    configuration:
      map-underscore-to-camel-case: true
firebase:
  api-key: ${FIREBASE_API_KEY}
  auth-domain: ${FIREBASE_AUTH_DOMAIN}
  database-url: ${FIREBASE_DATABASE_URL}
  project-id: ${FIREBASE_PROJECT_ID}
  storage-bucket: ${FIREBASE_STORAGE_BUCKET}
  messaging-sender-id: ${FIREBASE_MESSAGING_SENDER_ID}
  app-id: ${FIREBASE_APP_ID}
