server:
  port: 8000
  tomcat:
    additional-tld-skip-patterns: '*.jar'

spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: '/WEB-INF/views/'
      suffix: '.jsp'
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: '10MB'
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/vitaltrack
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vitaltrack.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  executor-type: simple
